# Generated by Django 5.2.2 on 2025-06-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe', models.TextField(max_length=30)),
                ('backstory', models.TextField(max_length=300)),
                ('avatar', models.ImageField(upload_to='ps_app/avatars')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ps_app.post')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ps_app.post',),
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ps_app.post')),
                ('image', models.ImageField(upload_to='posts/images')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ps_app.post',),
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ps_app.post')),
                ('content', models.TextField(max_length=300)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ps_app.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ps_app.persona'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ps_app.post')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ps_app.persona')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ps_app.post')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ps_app.persona')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='Clash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('persona1', 'Persona 1 Wins'), ('persona2', 'Persona 2 Wins'), ('draw', 'Draw')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_initiator', to='ps_app.persona')),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_opponent', to='ps_app.persona')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('persona1', 'persona2', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UniverseMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_universe', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_as_initiator', to='ps_app.persona')),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_as_partner', to='ps_app.persona')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('persona1', 'persona2')},
            },
        ),
    ]
